// Generates a one-shot SQL seed script from the mock data, so it can be pasted
// straight into the Supabase SQL Editor (the anon/publishable key can't write
// under RLS, and we're not passing a service role key around).
import { randomUUID } from "crypto";
import { writeFileSync } from "fs";
import { OWNED } from "../src/lib/mock-artists";

const esc = (s: string) => s.replace(/'/g, "''");
const secs = (d: string) => {
  const [m, s] = d.split(":").map(Number);
  return m * 60 + s;
};

const lines: string[] = ["-- Generated by scripts/generate-seed.ts — seed data for the Pocket mockup artists.", "begin;"];

for (const a of OWNED) {
  const artistId = randomUUID();
  lines.push(
    `insert into artists (id, slug, name, discipline, based, country, lat, lng, bio, card_bg, card_ink, card_tint, joined_at) values ` +
      `('${artistId}', '${esc(a.slug)}', '${esc(a.name)}', null, '${esc(a.based)}', '${esc(a.country)}', ${a.geo.split(",")[0]}, ${a.geo.split(",")[1]}, '${esc(a.bio)}', '${esc(a.cardBg)}', '${esc(a.cardInk)}', '${esc(a.tint)}', '${esc(a.joined)} 01'::timestamptz);`
  );

  for (const c of a.contacts) {
    lines.push(`insert into artist_contacts (artist_id, kind, value) values ('${artistId}', '${c.kind}', '${esc(c.value)}');`);
  }

  const showIds: string[] = [];
  for (const sh of a.shows) {
    const showId = randomUUID();
    showIds.push(showId);
    lines.push(
      `insert into exhibitions (id, artist_id, title, kind, year, venue, lat, lng) values ` +
        `('${showId}', '${artistId}', '${esc(sh.title)}', '${sh.kind.toLowerCase()}', ${sh.year}, '${esc(sh.venue)}', ${sh.geo.split(",")[0]}, ${sh.geo.split(",")[1]});`
    );
  }

  a.art.forEach((w, i) => {
    const workId = randomUUID();
    const code = String(100000 + Math.floor(Math.random() * 899999));
    lines.push(
      `insert into artworks (id, artist_id, slug, code, title, duration_sec, description, listen_count, sort_order) values ` +
        `('${workId}', '${artistId}', '${esc(w.id)}', '${code}', '${esc(w.title)}', ${secs(w.durationLabel)}, '${esc(w.description)}', ${w.listenCount}, ${i});`
    );
    const showId = showIds[w.showIndex];
    if (showId) {
      lines.push(`insert into exhibition_artworks (exhibition_id, artwork_id) values ('${showId}', '${workId}');`);
    }
  });
}

lines.push("commit;");

const out = lines.join("\n");
writeFileSync(new URL("../../supabase/seed.sql", import.meta.url), out, "utf8");
console.log(`Wrote ${lines.length} lines to supabase/seed.sql`);
